---
- name: Enable r1soft repo.
  template:
    src: r1soft.repo.j2
    dest: /etc/yum.repos.d/r1soft.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: r1soft_yum_repo_enabled | bool

- name: Ensure r1soft is installed.
  package:
    name: "{{ r1soft_package_name }}"
    state: present

- name: Ensure Kernel Source is installed.
  package:
    name: "{{ r1soft_package_kernel }}"
    state: present
